3rd module - 1st task
js-tasks-ru/jsbasic-20240321_valeria-kurn pull request #3
Opened 2024-04-02 17:00 UTC by valeriakurn

2024-04-02 17:01 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-04-02 17:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-04-02 18:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-04-02 19:57 UTC, SinimaWath requested changes

2024-04-02 19:57 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return names
Давай тут заиспользуем map: `names.map(...)`

2024-04-02 19:57 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  return filtered
Давай тут заиспользуем: `filter->map`

2024-04-03 16:19 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-04-03 16:27 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-04-03 17:08 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-04-03 17:59 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-04-05 14:55 UTC, SinimaWath approved these changes
все круто!

2024-04-05 14:55 UTC, merged